// Sample package.json files for the demo. The projects are made up; the
// packages are real, because real ones are what visitors paste.

export const SAMPLES = [
  {
    id: 'store',
    label: 'SvelteKit store',
    icon: 'store',
    pkg: {
      name: 'tidepool-store',
      version: '0.8.2',
      private: true,
      description: 'Small-batch ceramics, fired on the coast.',
      type: 'module',
      packageManager: 'pnpm@9.15.4',
      engines: { node: '>=20' },
      scripts: {
        dev: 'vite dev',
        build: 'vite build',
        preview: 'vite preview',
        check: 'svelte-kit sync && svelte-check --tsconfig ./tsconfig.json',
        'db:migrate': 'drizzle-kit migrate',
        test: 'vitest',
      },
      dependencies: {
        '@auth/sveltekit': '^1.7.4',
        bcrypt: '^5.1.1',
        'date-fns': '^4.1.0',
        'drizzle-orm': '^0.38.3',
        'lucide-svelte': '^0.469.0',
        marked: '^15.0.4',
        nanoid: '^5.0.9',
        postgres: '^3.4.5',
        sharp: '^0.33.5',
        ws: '^8.18.0',
        zod: '^3.24.1',
      },
      devDependencies: {
        '@sveltejs/adapter-auto': '^3.3.1',
        '@sveltejs/kit': '^2.15.1',
        '@sveltejs/vite-plugin-svelte': '^5.0.3',
        '@tailwindcss/vite': '^4.0.0',
        '@types/ws': '^8.5.13',
        dotenv: '^16.4.7',
        'drizzle-kit': '^0.30.1',
        eslint: '^9.17.0',
        prettier: '^3.4.2',
        'prettier-plugin-svelte': '^3.3.2',
        svelte: '^5.16.0',
        'svelte-check': '^4.1.1',
        tailwindcss: '^4.0.0',
        typescript: '^5.7.2',
        vite: '^6.0.6',
        vitest: '^2.1.8',
      },
    },
  },
  {
    id: 'saas',
    label: 'React SaaS + ORM',
    icon: 'chart',
    pkg: {
      name: 'ledgerline',
      version: '1.4.0',
      private: true,
      description: 'Invoices and cash flow for freelancers.',
      engines: { node: '22.x' },
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
        'db:push': 'prisma db push',
        'db:studio': 'prisma studio',
      },
      dependencies: {
        '@auth/prisma-adapter': '^2.7.4',
        '@prisma/client': '^6.1.0',
        '@tanstack/react-query': '^5.62.11',
        bcryptjs: '^2.4.3',
        clsx: '^2.1.1',
        'date-fns': '^4.1.0',
        next: '15.1.3',
        'next-auth': '5.0.0-beta.25',
        nodemailer: '^6.9.16',
        react: '19.0.0',
        'react-dom': '19.0.0',
        recharts: '^2.15.0',
        sharp: '^0.33.5',
        zod: '^3.24.1',
      },
      devDependencies: {
        '@types/node': '^22.10.2',
        '@types/nodemailer': '^6.4.17',
        '@types/react': '^19.0.2',
        eslint: '^9.17.0',
        'eslint-config-next': '15.1.3',
        postcss: '^8.4.49',
        prisma: '^6.1.0',
        tailwindcss: '^3.4.17',
        typescript: '^5.7.2',
      },
    },
  },
  {
    id: 'blog',
    label: 'Astro blog',
    icon: 'doc',
    pkg: {
      name: 'field-notes',
      type: 'module',
      version: '2.3.1',
      description: 'Notes on birding, maps and slow travel.',
      packageManager: 'npm@10.9.2',
      scripts: {
        dev: 'astro dev',
        build: 'astro check && astro build',
        preview: 'astro preview',
      },
      dependencies: {
        '@astrojs/check': '^0.9.4',
        '@astrojs/mdx': '^4.0.3',
        '@astrojs/rss': '^4.0.10',
        '@astrojs/sitemap': '^3.2.1',
        astro: '^5.1.1',
        'reading-time': '^1.5.0',
        sharp: '^0.33.5',
        typescript: '^5.7.2',
      },
    },
  },
  {
    id: 'api',
    label: 'Express + websockets',
    icon: 'bolt',
    pkg: {
      name: 'switchyard-api',
      version: '3.2.0',
      description: 'Dispatch API with live driver positions.',
      main: 'src/server.js',
      engines: { node: '>=18.17' },
      scripts: {
        start: 'node src/server.js',
        dev: 'nodemon src/server.js',
        test: 'jest',
        lint: 'eslint src',
      },
      dependencies: {
        bcrypt: '^5.1.1',
        cors: '^2.8.5',
        dotenv: '^16.4.7',
        express: '^4.21.2',
        helmet: '^8.0.0',
        jsonwebtoken: '^9.0.2',
        morgan: '^1.10.0',
        multer: '^1.4.5-lts.1',
        'node-cron': '^3.0.3',
        nodemon: '^3.1.9',
        pg: '^8.13.1',
        'socket.io': '^4.8.1',
      },
      devDependencies: {
        eslint: '^9.17.0',
        jest: '^29.7.0',
        supertest: '^7.0.0',
      },
    },
  },
  {
    id: 'vue',
    label: 'Vue SSR app',
    icon: 'layout',
    pkg: {
      name: 'harbor-bookings',
      private: true,
      type: 'module',
      version: '0.3.0',
      description: 'Mooring reservations for small marinas.',
      packageManager: 'yarn@4.6.0',
      scripts: {
        build: 'nuxt build',
        dev: 'nuxt dev',
        generate: 'nuxt generate',
        preview: 'nuxt preview',
        postinstall: 'nuxt prepare',
      },
      dependencies: {
        '@nuxt/image': '^1.8.1',
        '@nuxtjs/i18n': '^9.1.1',
        '@pinia/nuxt': '^0.9.0',
        '@vueuse/nuxt': '^12.2.0',
        mongoose: '^8.9.2',
        nuxt: '^3.15.0',
        pinia: '^2.3.0',
        vue: '^3.5.13',
        'vue-router': '^4.5.0',
      },
    },
  },
  {
    id: 'monorepo',
    label: 'Monorepo root',
    icon: 'stack',
    pkg: {
      name: 'orbit',
      private: true,
      packageManager: 'npm@10.9.2',
      engines: { node: '>=22' },
      workspaces: ['apps/*', 'packages/*'],
      scripts: {
        build: 'npm run build --workspaces --if-present',
        dev: 'npm run dev --workspace apps/web',
        lint: 'eslint .',
        changeset: 'changeset',
        release: 'changeset publish',
        prepare: 'husky',
      },
      devDependencies: {
        '@changesets/cli': '^2.27.11',
        eslint: '^9.17.0',
        husky: '^9.1.7',
        'lint-staged': '^15.2.11',
        prettier: '^3.4.2',
        typescript: '^5.7.2',
      },
    },
  },
  {
    id: 'tricky',
    label: 'The tricky one',
    icon: 'alert',
    pkg: {
      name: 'pagemill',
      version: '0.9.4',
      description: 'Turns web pages into PDFs and social images.',
      engines: { node: '>=18' },
      scripts: {
        dev: 'vite',
        build: 'vite build',
        start: 'node server/index.js',
        postinstall: 'node scripts/fetch-fonts.mjs',
      },
      dependencies: {
        'better-sqlite3': '^11.7.0',
        bullmq: '^5.34.6',
        canvas: '^2.11.2',
        dotenv: '^16.4.7',
        express: '^4.21.2',
        ioredis: '^5.4.2',
        'node-cron': '^3.0.3',
        'pdf-lib': '^1.17.1',
        puppeteer: '^23.11.1',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
        sharp: '^0.33.5',
        zod: '^3.24.1',
      },
      devDependencies: {
        '@vitejs/plugin-react': '^4.3.4',
        typescript: '^5.7.2',
        vite: '^6.0.6',
      },
    },
  },
];

export const DEFAULT_SAMPLE = 'store';

/** The sample as a visitor would paste it: two-space JSON. */
export function sampleText(id) {
  const sample = SAMPLES.find((s) => s.id === id);
  return sample ? `${JSON.stringify(sample.pkg, null, 2)}\n` : '';
}
