export default {
  id: 'kai',
  name: 'Kai',
  greeting: 'Hey! Planning an escape? I can help you pick a room.',
  quirk: 'headset',
  build: { legs: 15 },
  palette: {
    s: '#8d5a3b', S: '#6e4128',
    m: '#4e231e', e: '#170d14',
    h: '#231b22', H: '#3d3139', j: '#4d3f4a',
    g: '#3a3f4a', G: '#646d7e', a: '#e0453a',
    t: '#f2c230', T: '#c9941c', y: '#ffe07a',
    w: '#f7f3ea',
    p: '#2e2d3d', P: '#1d1c29',
    f: '#f2f0ea', F: '#b3aca0',
  },
  head: {
    front: [
      '..................',
      '.......h..h.......',
      '....hhhhhhhhhh....',
      '...hhjhhhhhjhhh...',
      '..gggggggggggggg..',
      '..ghhhhhhhhhhhhg..',
      '..ghHhhhhhhhhHhg..',
      '..gHssssssssssHg..',
      '..gHssssssssssHg..',
      '.GgsshhhsshhhssgG.',
      '.GgssssssssssssgG.',
      '.GgssssssssssssgG.',
      '.GggsssssSsssssgG.',
      '...sgssssssssss...',
      '....sgasssssss....',
      '.....SssssssS.....',
      '.......SSSS.......',
      '.......ssss.......',
    ],
    side: [
      '..................',
      '......h..h........',
      '....hhhhhhhh......',
      '...hhjhhhjhhhh....',
      '..hhhhhgghhhhhh...',
      '..hhhhhgghhhhhhh..',
      '..HhhhhgghhhhSss..',
      '..HHhhhgghhhssss..',
      '..HHhhhgghhsssss..',
      '..HHhhGggGsshhss..',
      '..HHhhGggGssssss..',
      '..HHhhGggGsssssss.',
      '...HhhGggGgssssS..',
      '....hhsssssggass..',
      '.....hssssssssss..',
      '......SsssssssS...',
      '........SSS.......',
      '........sss.......',
    ],
    back: [
      '..................',
      '.......h..h.......',
      '....hhhhhhhhhh....',
      '...hhjhhhhhjhhh...',
      '..gggggggggggggg..',
      '..ghhhhhhhhhhhhg..',
      '..ghhhhjhhhhhhhg..',
      '..ghhhhhhhhhhhhg..',
      '..gHhhhhhhhhhhHg..',
      '.GgHHhhhhhhhhHHgG.',
      '.GgHHHHHHHHHHHHgG.',
      '.GgSHHHHHHHHHHSgG.',
      '.GggSSSSSSSSSSggG.',
      '...ssssssssssss...',
      '....ssssssssss....',
      '.....SssssssS.....',
      '.......SSSS.......',
      '.......ssss.......',
    ],
  },
  face: {
    front: { eyes: [[6, 10], [11, 10]], mouth: [8, 13] },
    side: { eye: [13, 10], mouth: [14, 14] },
  },
  torso: {
    front: [
      '....tTTTTTTTTt....',
      '..ttttTwttwTtttt..',
      '..tttttwttwttttt..',
      '..tttttwttwttttt..',
      '..tttttwtttttttt..',
      '..tttttttttttttt..',
      '..ttttTTTTTTtttt..',
      '..tttTttttttTttt..',
      '..tttTttttttTttt..',
      '..ttTttttttttTtt..',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..TTTTTTTTTTTTTT..',
      '...pppppppppppp...',
      '..................',
      '..................',
      '..................',
      '..................',
    ],
    side: [
      '....TTTTtt........',
      '...TTTTtttttt.....',
      '....TTttttttw.....',
      '....tttttttttw....',
      '....tttttttttt....',
      '....tttttttttt....',
      '....tttttttttt....',
      '....tttttttttT....',
      '....tttttttttT....',
      '....tttttttttT....',
      '....tttttttttt....',
      '....tttttttttt....',
      '....TTTTTTTTTT....',
      '.....pppppppp.....',
      '..................',
      '..................',
      '..................',
      '..................',
    ],
    back: [
      '....tTTTTTTTTt....',
      '..ttTTTTTTTTTTtt..',
      '..ttTTTTTTTTTTtt..',
      '..tttTTTTTTTTttt..',
      '..ttttTTTTTTtttt..',
      '..tttttTTTTttttt..',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..TTTTTTTTTTTTTT..',
      '...pppppppppppp...',
      '..................',
      '..................',
      '..................',
      '..................',
    ],
  },
};
