export default {
  id: 'otto',
  name: 'Otto',
  greeting: 'Ahoy! Need a hint? I hid most of them myself.',
  quirk: 'beard',
  build: { shoulders: 8 },
  palette: {
    s: '#e2a47c', S: '#bf7d5a',
    h: '#7d6d62', H: '#5b4d44',
    b: '#7a4a2a', B: '#57331a',
    a: '#c7403a', A: '#962c2a',
    t: '#ebdfc4', T: '#c8b28a', y: '#f8f1df',
    p: '#30415f', P: '#1f2a42',
    f: '#6a4128', F: '#3f2415',
  },
  head: {
    front: [
      '..................',
      '..................',
      '......aaaaaa......',
      '....aaaaaaaaaa....',
      '...aaaaaaaaaaaa...',
      '...aaaaaaaaaaaa...',
      '..AAAAAAAAAAAAAA..',
      '..AAAAAAAAAAAAAA..',
      '..hssssssssssssh..',
      '..hssBBBssBBBssh..',
      '.shsssssssssssshs.',
      '.SbssssssssssssbS.',
      '..bbbsssSSsssbbb..',
      '..bbbbBBBBBBbbbb..',
      '..bbbbbbbbbbbbbb..',
      '...bbbbbbbbbbbb...',
      '....bbBbbbbBbb....',
      '......bbbbbb......',
    ],
    side: [
      '..................',
      '..................',
      '.....aaaaaa.......',
      '...aaaaaaaaaa.....',
      '..aaaaaaaaaaaa....',
      '..aaaaaaaaaaaaa...',
      '..AAAAAAAAAAAAA...',
      '..AAAAAAAAAAAAAA..',
      '..hhhhhhhsssssss..',
      '..hhhhhhssssBBBs..',
      '..hhhhsSssssssss..',
      '..hhhhsSbssssssS..',
      '..hhhhhbbbbssssSS.',
      '...hhhbbbbbbBBBb..',
      '....bbbbbbbbbbbb..',
      '.....bbbbbbbbbbb..',
      '......bbbbbBbbb...',
      '.......bbbbbbb....',
    ],
    back: [
      '..................',
      '..................',
      '......aaaaaa......',
      '....aaaaaaaaaa....',
      '...aaaaaaaaaaaa...',
      '...aaaaaaaaaaaa...',
      '..AAAAAAAAAAAAAA..',
      '..AAAAAAAAAAAAAA..',
      '..hhHhhhhHhhhHhh..',
      '..hHhhhHhhhhHhhh..',
      '.shhhHhhhhHhhhhhs.',
      '.ShHhhhhHhhhhHhhS.',
      '..bhhhHhhhhHhhhb..',
      '..bbHHHHHHHHHHbb..',
      '...bbSSSSSSSSbb...',
      '....bbssssssbb....',
      '......ssssss......',
      '.......ssss.......',
    ],
  },
  face: {
    front: { eyes: [[6, 10], [11, 10]], mouth: [8, 13] },
    side: { eye: [13, 10], mouth: [14, 14] },
  },
  torso: {
    front: [
      '....tttttttttt....',
      '..tttttttttttttt..',
      '..ttTtttTTtttTtt..',
      '..ttTtttTTtttTtt..',
      '..ttTtttTTtttTtt..',
      '..ttTtttTTtttTtt..',
      '..ttTtttTTtttTtt..',
      '..ttTtttTTtttTtt..',
      '..ttTtttTTtttTtt..',
      '..ttTtttTTtttTtt..',
      '..ttTtttTTtttTtt..',
      '..ttTtttTTtttTtt..',
      '..TTTTTTTTTTTTTT..',
      '...fffffyyfffff...',
      '..................',
      '..................',
      '..................',
      '..................',
    ],
    side: [
      '......tttt........',
      '....tttttttt......',
      '....ttttTtttt.....',
      '....ttttTttttt....',
      '....ttttTttttt....',
      '....ttttTttttt....',
      '....ttttTttttt....',
      '....ttttTttttt....',
      '....ttttTttttt....',
      '....ttttTttttt....',
      '....ttttTttttt....',
      '....ttttTttttt....',
      '....TTTTTTTTTT....',
      '.....ffffffff.....',
      '..................',
      '..................',
      '..................',
      '..................',
    ],
    back: [
      '....tttttttttt....',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..ttTtttttttttTt..',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..ttTtttttttttTt..',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..ttTtttttttttTt..',
      '..tttttttttttttt..',
      '..tttttttttttttt..',
      '..TTTTTTTTTTTTTT..',
      '...ffffffffffff...',
      '..................',
      '..................',
      '..................',
      '..................',
    ],
  },
};
