export default {
  id: 'vera',
  name: 'Vera',
  greeting: 'Psst! Stuck on something? I built these rooms. Ask me anything.',
  quirk: 'glasses',
  palette: {
    s: '#f1c29f', S: '#d4937a',
    h: '#c4582d', H: '#8c361b', j: '#e8834a',
    g: '#5b3a4e', k: '#eba38e',
    t: '#2f7a74', T: '#1f5654', y: '#58a597',
    a: '#f0b43c', A: '#c7892a',
    u: '#f4ecdc',
    p: '#4b3a52', P: '#34283b',
    f: '#7a4a2e', F: '#4e2e1c',
  },
  head: {
    front: [
      '..................',
      '......h.hh.h......',
      '....hhhhhhhhhh....',
      '...hhhjjhhhhhhh...',
      '..hhjhhhhhhhhjhh..',
      '.hhhhhhhhhhhhhhhh.',
      '.hhhjhhhhhhhhjhhh.',
      '.hhhhSssssssShhhh.',
      '.hhhsssssssssshhh.',
      '.hhssgggssgggsshh.',
      '.hhsgsssggsssgshh.',
      '.hHsgsssggsssgsHh.',
      '.hHssgggsSgggssHh.',
      '.hHhskssssssksHhh.',
      '..hHhsssssssshHh..',
      '...hh.SssssS.hh...',
      '.......SSSS.......',
      '.......ssss.......',
    ],
    side: [
      '..................',
      '......h.hh.h......',
      '....hhhhhhhhhh....',
      '..hhhjjhhhhhhhh...',
      '.hhjhhhhhhhhhhhh..',
      '.hhhhhhhhhhhhhhhh.',
      '.hhhhhhhhhjhhhhhh.',
      '.hhhhhhhhhhhhSsss.',
      '.hhhhhhhhhhhssss..',
      '.hhhhhhhhhhsgggs..',
      '.hhhhhhhhhgggsgs..',
      '.hhhhhhhhhssgsgss.',
      '.hhhhhhhhhssgggsS.',
      '.hHhhhhhhhssssss..',
      '..hHhhhhh.sssss...',
      '...hhhhh..SssS....',
      '........SSS.......',
      '........sss.......',
    ],
    back: [
      '..................',
      '......h.hh.h......',
      '....hhhhhhhhhh....',
      '...hhhjjhhhhhhh...',
      '..hhjhhhhhhhhjhh..',
      '.hhhhhhhhhhhhhhhh.',
      '.hhhjhhhhhhhhjhhh.',
      '.hhhhhhhhhhhhhhhh.',
      '.hhhhhhhjhhhhhhhh.',
      '.hhhhhhhhhhhhhhhh.',
      '.hhhhjhhhhhhjhhhh.',
      '.hHhhhhhhhhhhhhHh.',
      '.hHhhhhhhhhhhhhHh.',
      '.hHHhhhhhhhhhhHHh.',
      '..hHHhhhhhhhhHHh..',
      '...hhHHHHHHHHhh...',
      '.......SSSS.......',
      '.......ssss.......',
    ],
  },
  face: {
    front: { eyes: [[6, 10], [11, 10]], mouth: [8, 13] },
    side: { eye: [13, 10], mouth: [14, 13] },
  },
  torso: {
    front: [
      '.....taaaaaat.....',
      '...ttTaaaaaaTtt...',
      '...tttTuaauTttt...',
      '...tttTuaauTttt...',
      '...tttTuaAuTttt...',
      '...tttTuuauTttt...',
      '...tttTuuauTttt...',
      '...tttTuuAuTttt...',
      '...tttTuuuuTttt...',
      '...tttTuuuuTttt...',
      '...tttTuuuuTttt...',
      '...tttTTuuTTttt...',
      '...tttTppppTttt...',
      '...tttTppppTttt...',
      '...tttT....Tttt...',
      '...tttT....Tttt...',
      '...TTTT....TTTT...',
      '..................',
    ],
    side: [
      '.......taaa.......',
      '.....tttaaaa......',
      '.....tttttaa......',
      '.....ttttttaa.....',
      '.....ttttttTa.....',
      '.....tttttttA.....',
      '.....ttttttTt.....',
      '.....ttttttTt.....',
      '.....ttttttTt.....',
      '.....ttttttTt.....',
      '.....ttttttTt.....',
      '.....ttttttTt.....',
      '.....ttttttTt.....',
      '.....ttttttTt.....',
      '....ttttttttT.....',
      '....ttttttttT.....',
      '....TTTTTTTTT.....',
      '..................',
    ],
    back: [
      '.....taaaaaat.....',
      '...ttaaaaaaaatt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...tttttTTttttt...',
      '...TTTTTTTTTTTT...',
      '..................',
    ],
  },
};
