// Axial's own issues: the eight questions teams ask most before switching,
// answered by the (fictional) Axial team. They are static page content, never
// part of a Stand conversation. The facts here match the prompt in app.js,
// so the AI Stand-in and these answers agree.

export const TEAM = { key: 'SW', name: 'Switching' };

// Teammates who answered the FAQ issues. Avatars are drawn from initials.
export const PEOPLE = {
  mara: { name: 'Mara Okafor', role: 'Migrations', hue: 262 },
  theo: { name: 'Theo Brandt', role: 'Solutions', hue: 174 },
  ines: { name: 'Ines Carvalho', role: 'Security', hue: 346 },
  jun: { name: 'Jun Watanabe', role: 'Product', hue: 36 },
};

// Dates are fixed, so the page reads the same next year.
export const SEEDED = [
  {
    id: 'SW-1',
    title: 'Can we import 40k issues with their history?',
    description: '40,000 issues since 2017, with comments, attachments and years of status history. Does all of it come with us?',
    priority: 'high',
    labels: ['migration'],
    assignee: 'mara',
    asked: 214,
    filed: '2026-06-03T09:12',
    answered: '2026-06-03T09:31',
    done: '2026-06-04T08:05',
    answer: 'All of it comes with you. Issues, comments, attachments, status history, sprints and links keep their original authors and dates, so an issue from 2017 still reads like 2017. If half your org can\'t move yet, SW-6 has you covered.\n\nA 40k import usually finishes in under an hour. Start with a dry run: it\'s free, and it lists anything that won\'t map before a single issue moves.',
  },
  {
    id: 'SW-2',
    title: 'Do our custom fields survive the move?',
    description: 'Our tracker has thirty-odd custom fields. Half are dropdowns, the rest are text, numbers and dates. What happens to them?',
    priority: 'medium',
    labels: ['migration', 'workflow'],
    assignee: 'mara',
    asked: 167,
    filed: '2026-06-11T14:40',
    answered: '2026-06-11T15:02',
    done: '2026-06-12T10:20',
    answer: 'They survive as the closest native thing. Select and multi-select fields become labels, so **Component: Billing** turns into a Billing label you can filter by. Text, number and date fields become issue properties.\n\nYou review the whole mapping before anything imports, and you can drop the fields nobody has touched in a year. Most teams keep fewer than they expected.',
  },
  {
    id: 'SW-3',
    title: 'What happens to our sprint velocity reports?',
    description: 'Leadership reviews velocity every sprint. If we switch mid-quarter, do the charts start from zero?',
    priority: 'medium',
    labels: ['workflow'],
    assignee: 'jun',
    asked: 141,
    filed: '2026-06-24T11:05',
    answered: '2026-06-24T11:48',
    done: '2026-06-25T09:00',
    answer: 'They don\'t. Past sprints import with their scope, completed work and dates, so your velocity charts pick up where the old ones stopped. Story points become estimates on the scale you already use: Fibonacci, powers of two or t-shirt sizes.\n\nSwitch at a sprint boundary and nobody sees the seam.',
  },
  {
    id: 'SW-4',
    title: 'Do you support SSO and SCIM?',
    description: 'Security won\'t sign off without SAML SSO, and we provision every account from our identity provider.',
    priority: 'urgent',
    labels: ['security'],
    assignee: 'ines',
    asked: 128,
    filed: '2026-07-08T16:20',
    answered: '2026-07-08T16:34',
    done: '2026-07-09T08:45',
    answer: 'Yes to both. SAML SSO comes with Plus, including enforced login and accounts created on first sign-in. SCIM provisioning comes with Enterprise, and it deprovisions people within minutes.\n\nWe share our SOC 2 Type II report and answer your security questionnaire before you sign anything. Where your data lives is in SW-7.',
  },
  {
    id: 'SW-5',
    title: 'How long does a switch usually take?',
    description: 'We\'re about 180 engineers in 14 teams. What does a realistic timeline look like?',
    priority: 'low',
    labels: ['migration'],
    assignee: 'theo',
    asked: 96,
    filed: '2026-07-21T10:02',
    answered: '2026-07-21T10:25',
    done: '2026-07-22T13:10',
    answer: 'Most teams your size run a one- to two-week pilot with a single team, then move everyone else over two to six weeks. The import is an afternoon. The rest is people getting used to fewer clicks.\n\nPilot with the team that complains most about your current tracker. They make the best case to everyone else.',
  },
  {
    id: 'SW-6',
    title: 'Can half the org stay on the old tool during the move?',
    description: 'Platform and data teams can\'t move until after their Q4 freeze. Everyone else wants to go now.',
    priority: 'high',
    labels: ['integrations', 'migration'],
    assignee: 'theo',
    asked: 88,
    filed: '2026-08-05T13:30',
    answered: '2026-08-05T13:41',
    done: '2026-08-06T09:15',
    answer: 'Yes. On Plus and Enterprise, two-way sync keeps Axial and your old tracker in step for up to 90 days: new issues, status changes and comments flow both ways.\n\nTeams move when they\'re ready, and links between teams keep working in both tools while they do.',
  },
  {
    id: 'SW-7',
    title: 'Where is our data stored?',
    description: 'We have customers in the EU, and legal wants to know where issue data lives.',
    priority: 'medium',
    labels: ['security'],
    assignee: 'ines',
    asked: 74,
    filed: '2026-08-19T08:50',
    answered: '2026-08-19T09:07',
    done: '2026-08-19T15:30',
    answer: 'You choose when you create the workspace: the US, or the EU in Frankfurt. Everything stays in that region, including attachments, search indexes and backups.\n\nAxial is SOC 2 Type II audited. Moving an existing workspace to the other region is an Enterprise service.',
  },
  {
    id: 'SW-8',
    title: 'Will our scripts and webhooks keep working?',
    description: 'A dozen scripts file issues from alerts, and webhooks feed our deploy pipeline. Old issue keys are all over our docs, too.',
    priority: 'low',
    labels: ['integrations'],
    assignee: 'jun',
    asked: 61,
    filed: '2026-09-02T15:15',
    answered: '2026-09-02T15:39',
    done: '2026-09-03T10:00',
    answer: 'The scripts need a small port; the links don\'t. Axial has a GraphQL API and webhooks for issue, comment and status events, and most teams port an alert script in an afternoon.\n\nImported issues keep their old keys as aliases, so a link to **OPS-1423** in a 2019 doc still opens the right issue.',
  },
];
